/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        outline: "#6f7883",
        "tertiary-container": "#00b17b",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#edf1f6",
        "primary-container": "#00a1ff",
        "secondary-fixed": "#c4e7ff",
        secondary: "#00668a",
        "surface-container-highest": "#dfe3e8",
        "on-tertiary-container": "#003b26",
        "on-tertiary": "#ffffff",
        "on-surface": "#171c20",
        "primary-fixed": "#cfe5ff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#3f4852",
        surface: "#f6faff",
        background: "#f6faff",
        "on-tertiary-fixed-variant": "#005236",
        tertiary: "#006c49",
        "inverse-surface": "#2c3135",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#004c69",
        "outline-variant": "#bec7d4",
        "on-secondary-fixed": "#001e2c",
        primary: "#00629e",
        "on-primary-fixed-variant": "#004a79",
        "primary-fixed-dim": "#9acbff",
        "on-primary": "#ffffff",
        "surface-container": "#eaeef3",
        "surface-container-low": "#f0f4f9",
        "surface-container-high": "#e4e9ee",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "margin-screen": "1.25rem",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "600" }],
        "title-sm": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        caption: ["11px", { lineHeight: "14px", letterSpacing: "0", fontWeight: "500" }],
        "title-md": ["18px", { lineHeight: "26px", letterSpacing: "0", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "500" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
